### ISSUE TITLE
Enable DVR mode

### ISSUE THREAD

**Issue by rafa8626** [openplayerjs/openplayerjs#146]
If a stream has the ability to go backward in time, player must be smart enough to enable the progress bar and allow the manipulation of the media in DVR mode.

Example to use: https://hlsyoufm.akamaized.net/hls/live/2016538/youfm/master.m3u8

**Comment by rafa8626** [comment]
@ampersand83 can you test this using the `2.0.0` branch in this project and let me know if it works for you, even removing the `showLiveProgress` config element, please?

**Comment by ampersand83** [comment]
Hi @rafa8626, I would really like to test it, but I can't figure out how to build the 2.0.0 branch. At first I am on a windows 10 machine that doesn't know unix shell commands. That's why I can't run the build script. I removed the "[ -d ./dist ] && rm -R ./dist;" part and deleted the dist directory manually, but know when running "npm run build" the error message "TS18002: The 'files' list in config file 'tsconfig.json' is empty." is thrown. Any idea what to do? Somehow typescript misses a configuration file I guess. Can you help me here?

**Comment by rafa8626** [comment]
@ampersand83 I’ll check what happened and bundle the dist files so you can use them for testing

**Comment by rafa8626** [comment]
@ampersand83 it is ready now; just download the dist files from the 2.0.0 branch and let me know if it worked for you as expected

**Comment by ampersand83** [comment]
@rafa8626 everything seems to work fine. But I'm not sure why you put the hls Livestream in a video element. It is an audio only livestream and hence should be loaded as an audio element I think. Apart from that the progressbar recognizes the livestream with a dvr window without me specifying  the showLiveProgress option.

**Comment by rafa8626** [comment]
@ampersand83 lol my bad; I was testing it quickly that I just threw it in the video area. But yes, we should be using it as part of the audio tag.

I'm glad that you didn't need the option and kept working as expected. I really thank you for your help on this. Closing this issue
