### ISSUE TITLE
Can not load HLS.js

### ISSUE THREAD

**Issue by shell1986** [openplayerjs/openplayerjs#18]
Rafa hello, after the last update I stopped loading hls.js.

On your site the latest version of the player is installed?

**Comment by rafa8626** [comment]
@supersh86 Yes in the website I'm using the latest version. Can you give me a URL that is not working for you?

**Comment by supersh86** [comment]
hi try this link 
https://anime.anidub.com/player/index2.php?vid=/s1/10486/1/5.mp4

**Comment by supersh86** [comment]
I understood what the problem was.
I had an old class in the video
  class = "om-player__media"

**Comment by supersh86** [comment]
https://codepen.io/anon/pen/ZqWXBB
I also had problems launching HLS video after an advertisement.

And the safari appeared native control player.
![Imgur](https://i.imgur.com/pAZ3Kjk.png)

**Comment by rafa8626** [comment]
Safari in desktop or in iPhone/iPad?

**Comment by rafa8626** [comment]
@supersh86 I just pushed a fix for HLS and Ads. Please check your master branch and let me know

**Comment by supersh86** [comment]
Safari in desktop.
I also began to notice that Detach media is constantly happening.
This destroys the work of CDNBye.

By the way, you can add an example of integration for your player on their project.

**Comment by rafa8626** [comment]
Can you point me where are you seeing the detach issue? That call is only being done when you set a new source or load the media

**Comment by supersh86** [comment]
Updated test link
https://anime.anidub.com/player/index2.php?vid=/s1/10486/1/5.mp4

openplayer.js
```
      if (this.media && typeof this.media.destroy === 'function') {
        this.media.destroy();
      }
```

**Comment by supersh86** [comment]
If you turn on the adblock, the problem disappears.

**Comment by rafa8626** [comment]
@supersh86 please download the master branch and test again. The controls won't be displayed in Safari desktop anymore and also I noticed an issue in Safari, since it was trying to use HLS.js instead of native per our previous conversations. So that is also fixed. The media won't be destroyed unless it is a different source. I noticed in your test file that you are using both `op-player op-player__media` classes, when you should be using `op-player__media` class only, since the first class will be used to automatically start the player, and in your case you need to use the Javascript approach to have more flexibility. Let me know, and thanks for reporting these bugs

**Comment by supersh86** [comment]
Its, work
