### ISSUE TITLE
Catching onAdError Event

### ISSUE THREAD

**Issue by Rubioli** [openplayerjs/openplayerjs#194]
In `IMA SDK` I can see that it has `onAdError` function/event, but I can't seem to find it as an event in the player. I have tried a few different ways, but it doesn't seem to work.

Is there any event in order to *catch* the **AdError** currently? If so, I would appreciate any help or suggesting.

The Event would be useful for adding fallback or doing other things in case VAST is empty.

*PS: I can see in the console it catches an empty VAST and gives this warning: `Ad warning: AdError 1009: The VAST response document is empty.`* 

Thanks in advance

**Comment by rafa8626** [comment]
@Rubioli you can use the `playererror` event, and to detect if it was related to the Ads, check the e.detail.type to match the proper error type and then detail.data will give you all the information you need:
```javascript
player.getElement().addEventListener('playererror', e => {
     if (e.detail.type === 'Ads') {
           console.log(e.detail.data);
     }
});
```
Let me know if that works for you; otherwise, I can add a `adsonerror` event for you if needed

**Comment by Rubioli** [comment]
Thanks a lot @rafa8626 Works like a charm.

Thanks for your help 💯 🥇
