### ISSUE TITLE
modular final file

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#200]
for reduce final size you can split file to many module and if anyone wanna use some future use that.
for example:

openplayerjs.main,js
openplayerjs.hls.js
openplayerjs.ads.js
openplayerjs.dash,js
openplayerjs.flv.js

and if I wanna use hls only:
use openplayerjs.main,js and openplayerjs.hls.js

**Comment by rafa8626** [comment]
Maybe if can reduce the size but it will increase the number of http requests depending on the media to support so it’s a trade-off.

**Comment by foadabdollahi** [comment]
ok
when you splite by module in use i some module and combine any module i need.and combined file small that full package and both of them load by one request.

**Comment by rafa8626** [comment]
I’ll check this for a future version but this will require serious refactor because the file types definition and instantiation happen in a very specific way inside a common file and to achieve what you want need to think how to do it without altering the current bundle since now many people use it without thinking about adding more files to load their media

**Comment by foadabdollahi** [comment]
ok, i think this is good idea for next versions
and you can add bundle file for some people that you say
