### ISSUE TITLE
Tooltip align

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#209]
tooltip alignment set in CSS,
I think it should better calculate from clicked button and set dynamically.

![image](https://user-images.githubusercontent.com/13816403/107847943-15871c00-6e05-11eb-884e-6c933fa9b920.png)

**Comment by rafa8626** [comment]
@foadabdollahi I’ll take a look at this. Thanks for reporting it

**Comment by rafa8626** [comment]
@foadabdollahi can you give me a sample URL where I can see the issue please?

**Comment by rafa8626** [comment]
@foadabdollahi disregard my comment above; please download the master branch and test if it works for you now. The CSS position should be right now. There's no need to use JS for these type of endeavors since the browser run smoother calculations and I found out a better way to set the position for the menu. Let me know so I can release this tomorrow if possible

**Comment by foadabdollahi** [comment]
great, it fixed.
