### ISSUE TITLE
incorrect behavior when instantiating multiple players in foreach loop

### ISSUE THREAD

**Issue by JustinWebDev** [openplayerjs/openplayerjs#221]
**Describe the bug**
When instantiating multiple players in a .foreach() loop, the players do not respond correctly to some configuration settings.

**To Reproduce**
1. Go to https://codepen.io/rafa8626/pen/ExxXvZx
2. add the following to the player configuration
`startTime: 10,
    startVolume: .5,`
3. observe the new players - the first one has the correct start time, but the volume control is messed up; the second one does not honor the start time, but the volume control is correct

**Expected behavior**
Both players would correctly reflect the configuration.

**Screenshots**
first player
![image](https://user-images.githubusercontent.com/40804543/111014710-a7ce0180-836a-11eb-8e99-721661f6ca84.png)

second player
![image](https://user-images.githubusercontent.com/40804543/111014715-af8da600-836a-11eb-8d7b-7b4af5b3cff4.png)

**Additional context**
Is there a different way to instantiate multiple players?  I also could not find a way to modify/interact with the player objects after they were created.

**Comment by rafa8626** [comment]
@JustinWebDev it's weird because the issue is not present outside of CodePen. The only thing I can't figure out yet is the volume in HLS since it doesn't autoplay and the `loadedmetadata` messes with it; once you start playing the streaming all works as expected. With regular MP4/MP3 everything is fine.
<img width="672" alt="Screen Shot 2021-03-24 at 6 57 42 PM" src="https://user-images.githubusercontent.com/910829/112394384-041e1300-8cd3-11eb-9e85-63fcdf1c7538.png">

**Comment by JustinWebDev** [comment]
@rafa8626 Glad to hear it is only in CodePen.  I'm sure you'll figure out the rest   :-)
