### ISSUE TITLE
Chromecast

### ISSUE THREAD

**Issue by ReArno** [openplayerjs/openplayerjs#243]
**Describe the solution you'd like**
Chromecast functionality.
Im not sure, but I don't find this in the examples.

**Comment by rafa8626** [comment]
@ReArno the player by itself currently doesn’t have the code to make it work with Chromecast. For that it will be needed a custom control.

 Let me know if you need more details and please give the project a star to show your support

**Comment by ReArno** [comment]
Hi, Yes if you can provide more details it will be fine.

**Comment by ReArno** [comment]
@rafa8626  Let me know if you need more info.

**Comment by rafa8626** [comment]
@ReArno sorry for the delay, I’ve been busy lately. So for this one it requires the addition of a custom control but also it requires a new player to make Chromecast to work.

I created a custom plugin for another player long time ago, but it still uses the proper concept to make it work: https://github.com/mediaelement/mediaelement-plugins/tree/master/src/chromecast

In order to make this work, I need to add some elements in the control aspect, but this should give you a good start to understand how to do it.

Other than that you can also use the Presentation API but I’m not familiar with it 100%

**Comment by rafa8626** [comment]
@ReArno I may give it a try and create a Chromecast/Airplay plugin for it. I’ll let you know when I have some progress. Closing this for now
