### ISSUE TITLE
Mobile video ad click area

### ISSUE THREAD

**Issue by trampolinstudio** [openplayerjs/openplayerjs#256]
When mobile ad prerolls are played, there is a Learn more button on the top right corner.

Is there a possibility to enable customisation of this button?

Thank you!

**Comment by rafa8626** [comment]
@trampolinstudio please download the master branch and add this inside the `ads` configuration:
```javascript
ads: {
    customClick: {
         enabled: true,
         label: [YOUR LABEL],
    }
}
```

**Comment by trampolinstudio** [comment]
Thanks a lot!

**Comment by draganpetos** [comment]
Hi @rafa8626
This feature does not seem to be working. I've tested on our project and on your Codepen, where the label on mobile says 'Learn more' instead of 'Click here'.

I would have another suggestion/feature request, would it be possible to add another option to pass in inline styles to the label (.videoAdUiTopBar)?
 
In some cases, this would be very useful to be able to control the appearance of the label and we could change the position of the label, gradient, etc.

**Comment by rafa8626** [comment]
@draganpetos thanks for noticing this; the feature works when you set the source right from the beginning but this CodePen creates the Ad at any moment and something was missing; I’ll check that. In terms of styles, once the custom area is visible, you can tweak CSS as you please within your own CSS file. I’ll keep you posted about it

**Comment by rafa8626** [comment]
@draganpetos turn out that it works correctly, it had a typo in the CodePen code, and also in the documentation. Once I changed that it worked as expected. So you should be good to use it and tweak styles using CSS with the new layer enabled. Thanks

**Comment by draganpetos** [comment]
@rafa8626 thanks for the clarification and the update. Everything works as expected, nicely done with the label rendered outside the iframe, meaning we can customize it, which is just what we need!
Thanks a lot!

**Comment by rafa8626** [comment]
You are welcome! Glad this worked as expected for you!
