### ISSUE TITLE
The sound is a little delayed, when the hidden (second) player displayed

### ISSUE THREAD

**Issue by matranovakifanyuvo** [openplayerjs/openplayerjs#356]
Hello,

Please see this: [codepen.io](https://codepen.io/matranovakifanyuvo/pen/JjLwqKv)

1. Play.
2. Scroll down.

The footer player displayed, it works, but I have a little problem: the sound is a little delayed/jumped. Can you solve my problem?

Thanks.

**Comment by rafa8626** [comment]
@matranovakifanyuvo thanks for reaching out; I do think that your problem may be solved if you just use 1 player rather than 2 and, when scrolling, you apply a new class to a player wrapper to move its position. Let me know if that makes sense, since doing things with the playing event can create these types of issues

**Comment by rafa8626** [comment]
@matranovakifanyuvo thanks for reaching out; I do think that your problem may be solved if you just use 1 player rather than 2 and, when scrolling, you apply a new class to a player wrapper to move its position. Let me know if that makes sense, since doing things with the playing event can create these types of issues. 

Also, can you give the project a star to show your support to it, please?

**Comment by matranovakifanyuvo** [comment]
Starred. Thank you for your quick reply. "if you just use 1 player rather than 2 and, when scrolling, you apply a new class to a player wrapper to move its position" - can you give an example of this?

**Comment by rafa8626** [comment]
Check this CodePen: https://codepen.io/rafa8626/pen/xxWMXYz
