### ISSUE TITLE
Async Playback is getting blocked on Safari and iOS

### ISSUE THREAD

**Issue by afkcodes** [openplayerjs/openplayerjs#369]
**Describe the bug**
I am trying to fetch the audio url and then play with openplayer but it throws an error
`
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to (https://radio-india-afkcodes.vercel.app/)
2. Click on any song tile
3. Open console
4. See the error

**Expected behaviour**
Playback should not be blocked and should play smoothly, I am not even doing auto-play

**Screenshots**
<img width="1318" alt="Screenshot 2022-11-08 at 9 44 50 PM" src="https://user-images.githubusercontent.com/17390257/200617944-460fb72b-6fcc-4fdf-8438-89696e9f8c2a.png">

**Desktop (please complete the following information):**
 - OS: macOS [Monterey] 12.5.1
 - Browser safari
 - Version 15.6.1 

**Smartphone (please complete the following information):**
 - Device: iphone 12, iPhoneX
 - OS: iOS 16, 
 - Browser: safari, chrome
 - Version: NA

**Additional context**
Here is the repo: https://github.com/afkcodes/radio_india/commits/test/async
please check the latest commit and please let me know if i am doing anything wrong

**Comment by rafa8626** [comment]
@afkcodes the URL you provided is down. I can check the last commit but it will be more beneficial to see the issue in action

**Comment by afkcodes** [comment]
hello @rafa8626 the url is working fine at my end. can you please check or attach a screenshot.

**Comment by rafa8626** [comment]
@afkcodes yes now it’s up. I’ll check it and get back to you

**Comment by afkcodes** [comment]
thanks @rafa8626

**Comment by rafa8626** [comment]
@afkcodes I don't see any issues with your code and I haven't seen the issue you described in your site using iOS; the only one I've seen is related to Network errors. I would say that your code is fine, but you do need to introduce a UI element to wait for the response back before audio starts playing, because if it takes longer than expected to get the URL processed by the server, the user can think something is wrong (like I did the first time). I hope that helps
