### ISSUE TITLE
Project status: PR welcome

### ISSUE THREAD

**Issue by aliraza-noon** [openplayerjs/openplayerjs#408]
Thank you for your time and effort you have invested in this project.

I wanted to understand what is the long term goal for this project do you plan working on this as I see this below notice on the readme.

```
🚨 IMPORTANT 🚨
🔧 This repository is in maintenance at this point. 🔧
No new features or additions will be added, only bug fixes.
```

**Comment by rafa8626** [comment]
@aliraza-noon thanks for reaching out. Work and life had gotten busier for me, hence why I put that statement in the project. 

The idea is to launch the version 3 of this project at some point, but one of the main goals (reach at least 70% of coverage in unit tests) had turned more difficult than I thought. Using Jest is neat but as I’m testing I need to do more research to mock what the browser will perform when playing a video, and that needs more research on my end.

I’m not archiving the project, since I want to improve the project. Just need my schedule to clear some. Also, I’m welcoming pull requests to fix issues or to do some work for the v3.0 branch.

I hope this helps to clarify a little the future of this project. If you have any more questions, please let me know

**Comment by aliraza-noon** [comment]
> Work and life had gotten busier for me, hence why I put that statement in the project.

I can understand as someone being in similar position 

> I’m not archiving the project, since I want to improve the project. Just need my schedule to clear some. Also, I’m welcoming pull requests to fix issues or to do some work for the v3.0 branch.

I have no experience in multimedia, I am just a user of libraries like this one and have used and paid for certain commercial packages for some projects i developed and not satisfied with what I received in return for the money I paid.

I wish to dig deep and learn more about multimedia technology and if time permits start a project (wanted to name it openplayer 😄 ) that will be totally free, so started doing research on internet to find more resources and came across this project.

Thank you for taking the time and replying to this comment and explaining the long term goal.

**Comment by rafa8626** [comment]
@aliraza-noon you are welcome. If things change in the near future, I’ll let you know. In the mean time, can I ask you to give the project a star to show your support? It would be greatly appreciated

**Comment by JustinWebDev** [comment]
@rafa8626  are the docs impacted or updated for V3?
