### ISSUE TITLE
The manifest is loaded for a long time, if there is a vast.

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#55]
Hi, I have long wanted to raise the topic of a long loading of manifests. If the vast is connected to the player, the manifest will take a long time to load or will not load at all until the user starts the player. You can notice this problem on your main page in the example with advertising.

**Comment by rafa8626** [comment]
@supersh86 The mechanism I implemented for Ads was following the examples given by IMA SDK to be complaint with mobile and desktop behaviors; if you add `autoplay` to the video tag, it will play faster since it starts to load the Ads immediately; otherwise, you will have to click play to save bandwidth and load Ads. Is that what your concern is?

**Comment by supersh86** [comment]
I understand it. Just visually it looks like it is not working.

I have one more question, do you have tools that catch the error google ima?

**Comment by rafa8626** [comment]
No just use the console to check errors right now
